const express=require("express"),{Pool}=require("pg"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),path=require("path");
const app=express(),PORT=process.env.PORT||10000;
if(!process.env.DATABASE_URL||!process.env.JWT_SECRET||!process.env.OWNER_EMAIL||!process.env.OWNER_PASSWORD)process.exit(1);
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes("localhost")?false:{rejectUnauthorized:false}});
app.use(express.json());app.use(express.static(path.join(__dirname,"public")));
async function init(){await pool.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'student',created_at TIMESTAMPTZ DEFAULT NOW());CREATE TABLE IF NOT EXISTS lectures(id SERIAL PRIMARY KEY,module_no INT NOT NULL,level TEXT NOT NULL,title TEXT NOT NULL,description TEXT DEFAULT '',video_url TEXT DEFAULT '',resource_url TEXT DEFAULT '',created_at TIMESTAMPTZ DEFAULT NOW());`);let h=await bcrypt.hash(process.env.OWNER_PASSWORD,12);await pool.query("INSERT INTO users(email,password_hash,role) VALUES($1,$2,'owner') ON CONFLICT(email) DO UPDATE SET role='owner',password_hash=$2",[process.env.OWNER_EMAIL.toLowerCase(),h])}
function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||"").split(" ")[1],process.env.JWT_SECRET);next()}catch{res.status(401).json({error:"Login required"})}}
function owner(req,res,next){if(req.user.role!=="owner")return res.status(403).json({error:"Owner only"});next()}
app.get("/health",async(_,res)=>{try{await pool.query("SELECT 1");res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.post("/api/login",async(req,res)=>{let e=String(req.body.email||"").toLowerCase().trim(),p=String(req.body.password||""),q=await pool.query("SELECT * FROM users WHERE email=$1",[e]);if(!q.rowCount||!(await bcrypt.compare(p,q.rows[0].password_hash)))return res.status(401).json({error:"Invalid email or password"});let u=q.rows[0];res.json({token:jwt.sign({id:u.id,email:u.email,role:u.role},process.env.JWT_SECRET,{expiresIn:"7d"}),user:{id:u.id,email:u.email,role:u.role}})});
app.get("/api/me",auth,(req,res)=>res.json({user:req.user}));
app.get("/api/lectures",async(_,res)=>res.json({lectures:(await pool.query("SELECT * FROM lectures ORDER BY module_no,id")).rows}));
app.get("/api/students",auth,owner,async(_,res)=>res.json({students:(await pool.query("SELECT id,email,created_at FROM users WHERE role='student' ORDER BY id DESC")).rows}));
app.post("/api/students",auth,owner,async(req,res)=>{let e=String(req.body.email||"").toLowerCase().trim(),p=String(req.body.password||"");if(!e||p.length<6)return res.status(400).json({error:"Valid email and 6+ character password required"});try{let h=await bcrypt.hash(p,12),q=await pool.query("INSERT INTO users(email,password_hash,role) VALUES($1,$2,'student') RETURNING id,email,role,created_at",[e,h]);res.status(201).json({user:q.rows[0]})}catch(x){res.status(x.code==="23505"?409:500).json({error:x.code==="23505"?"Email already exists":"Could not create account"})}});
app.delete("/api/students/:id",auth,owner,async(req,res)=>{await pool.query("DELETE FROM users WHERE id=$1 AND role='student'",[req.params.id]);res.json({ok:true})});
app.post("/api/lectures",auth,owner,async(req,res)=>{let n=Number(req.body.module_no),t=String(req.body.title||"").trim();if(!Number.isInteger(n)||n<1||!t)return res.status(400).json({error:"Module number and title required"});let q=await pool.query("INSERT INTO lectures(module_no,level,title,description,video_url,resource_url) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[n,String(req.body.level||"Beginner"),t,String(req.body.description||""),String(req.body.video_url||""),String(req.body.resource_url||"")]);res.status(201).json({lecture:q.rows[0]})});
app.delete("/api/lectures/:id",auth,owner,async(req,res)=>{await pool.query("DELETE FROM lectures WHERE id=$1",[req.params.id]);res.json({ok:true})});
app.get("*",(_,res)=>res.sendFile(path.join(__dirname,"public/index.html")));
init().then(()=>app.listen(PORT,"0.0.0.0")).catch(e=>{console.error(e);process.exit(1)});
